import streamlit as st
import os
from typing import Literal
from pydantic import BaseModel, Field
import google.generativeai as genai


# 1. UI CONFIGURATION

st.set_page_config(page_title="Case Creation Agent", layout="wide")
st.title("📝 Automated Case Creation Agent")
st.markdown("### Multi-Agent Pipeline: Node 3 (System Integration)")


# 2. SECURE API KEY HANDLING

try:
    api_key = st.secrets["GEMINI_API_KEY"]
    os.environ["GEMINI_API_KEY"] = api_key
    genai.configure(api_key=api_key)
except KeyError:
    st.error("⚠️ **Setup Error:** GEMINI_API_KEY not found in secrets.")
    st.stop()


# 3. SCHEMA DEFINITION (The CRM/ERP Case Record)

PriorityLevel = Literal["LOW", "MEDIUM", "HIGH", "URGENT"]

class CaseRecord(BaseModel):
    case_title: str = Field(description="A short, standardized title for the case (e.g., 'New Business Submission - Acme Corp').")
    priority: PriorityLevel = Field(description="Determine SLA priority based on intent and missing data.")
    assigned_queue: str = Field(description="The specific operational team this should be routed to (e.g., 'Bulk Processing Team', 'Standard Review Team', 'Exceptions Desk').")
    executive_summary: str = Field(description="A 2-3 sentence summary of the case for the human reviewer to read immediately upon opening the ticket.")
    flagged_issues: str = Field(description="List any missing fields or anomalies that the human must address. Output 'None' if perfectly clean.")
    crm_payload: str = Field(description="A stringified JSON object representing the final payload to be pushed via API to the core system.")


# 4. INITIALIZE THE CASE CREATION MODEL

@st.cache_resource
def get_synthesis_agent():
    return genai.GenerativeModel(
        model_name="gemini-2.5-flash",
        system_instruction=(
            "You are an elite System Integration AI. Your objective is to take raw, extracted data "
            "and the routing classification from previous agent nodes, and synthesize them into a "
            "clean, standardized Case Record ready for CRM ingestion. "
            "Assess the completeness of the data. If data is missing (e.g., 'MISSING' values), elevate the priority "
            "and flag the issue. Draft a concise summary for the human operator."
        )
    )

model = get_synthesis_agent()

# 5. USER INTERFACE (Simulating the Data Handoff)

st.sidebar.info(
    "💡 **Pipeline Context:** In production, this agent automatically receives the JSON outputs "
    "from Node 1 and Node 2. It synthesizes them into a final system-of-record ticket and triggers "
    "the API push to the CRM."
)

st.markdown("#### Step 1: Simulate Inbound Agent Payloads")
st.write("For this PoC, paste the JSON outputs generated by the previous nodes to see how the Case Agent synthesizes them.")

col1, col2 = st.columns(2)

with col1:
    extracted_data_input = st.text_area(
        "Payload from Node 1 (Structured Extractor)", 
        height=250,
        value='{\n  "client_name": "TechGlobal Industries",\n  "contact_info": "MISSING",\n  "document_type": "Standard Application",\n  "total_limits": "$5,000,000"\n}'
    )

with col2:
    intent_data_input = st.text_area(
        "Payload from Node 2 (Intent Classifier)", 
        height=250,
        value='{\n  "intent_category": "STANDARD_PROCESSING",\n  "confidence_score": 98,\n  "flags": "None"\n}'
    )

st.divider()

if st.button("⚙️ Generate CRM Case Record", type="primary", use_container_width=True):
    with st.spinner("Synthesizing multi-agent data into system record..."):
        try:
            # Combine the payloads into a single prompt for the model
            synthesis_prompt = f"""
            Synthesize the following upstream agent payloads into a final Case Record.
            
            NODE 1 PAYLOAD (Data):
            {extracted_data_input}
            
            NODE 2 PAYLOAD (Intent):
            {intent_data_input}
            """
            
            response = model.generate_content(
                contents=[synthesis_prompt],
                generation_config=genai.GenerationConfig(
                    response_mime_type="application/json",
                    response_schema=CaseRecord,
                    temperature=0.1
                )
            )
            
            # Validate JSON to Pydantic
            case = CaseRecord.model_validate_json(response.text)
            
            # Display the Final Dashboard
            st.success("✅ Case Record Synthesized Successfully")
            
            # Top row metrics
            m_col1, m_col2, m_col3 = st.columns(3)
            with m_col1:
                st.metric("Priority SLA", case.priority)
            with m_col2:
                st.metric("Assigned Queue", case.assigned_queue)
            with m_col3:
                if case.flagged_issues != "None":
                    st.error("⚠️ Action Required")
                else:
                    st.success("✨ Ready for Processing")

            st.markdown(f"### 📋 {case.case_title}")
            
            st.markdown("#### Executive Summary")
            st.info(case.executive_summary)
            
            st.markdown("#### Flagged Issues")
            if case.flagged_issues == "None":
                st.write("✅ All critical data points present.")
            else:
                st.warning(case.flagged_issues)
                
            st.markdown("#### Generated System API Payload")
            st.json(case.crm_payload)
            
        except Exception as e:
            st.error(f"Synthesis failed: {str(e)}")